In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Nassau Candy Distributor.csv")
df.shape

(10194, 18)

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB

In [3]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID         int64
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Division              str
Region                str
Product ID            str
Product Name          str
Sales             float64
Units               int64
Gross Profit      float64
Cost              float64
dtype: object

In [6]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed')

In [7]:
df[['Order Date', 'Ship Date']].head(20)

   Order Date  Ship Date
0  2024-03-01 2026-06-30
1  2024-04-01 2026-01-07
2  2024-04-01 2026-01-07
3  2024-04-01 2026-01-07
4  2024-05-01 2026-05-07
5  2024-06-01 2026-03-07
6  2024-06-01 2026-03-07
7  2024-06-01 2026-06-30
8  2024-06-01 2026-03-07
9  2024-06-01 2026-03-07
10 2024-06-01 2026-03-07
11 2024-06-01 2026-01-07
12 2024-06-01 2026-03-07
13 2024-06-01 2026-03-07
14 2024-07-01 2026-05-07
15 2024-07-01 2026-05-07
16 2024-09-01 2026-06-07
17 2024-09-01 2026-06-07
18 2024-10-01 2026-08-07
19 2024-10-01 2026-08-07

In [8]:
df[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [9]:
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [10]:
df[['Order Date', 'Ship Date', 'Shipping Days']].head()

  Order Date  Ship Date  Shipping Days
0 2024-03-01 2026-06-30            851
1 2024-04-01 2026-01-07            646
2 2024-04-01 2026-01-07            646
3 2024-04-01 2026-01-07            646
4 2024-05-01 2026-05-07            736

In [11]:
df['Order Date'].min(), df['Order Date'].max()

(Timestamp('2024-01-02 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [12]:
df['Ship Date'].min(), df['Ship Date'].max()

(Timestamp('2026-01-07 00:00:00'), Timestamp('2030-12-06 00:00:00'))

In [13]:
df['Shipping Days'].describe()

count    10194.000000
mean      1344.239356
std        294.675072
min        491.000000
25%       1194.000000
50%       1276.000000
75%       1638.000000
max       1965.000000
Name: Shipping Days, dtype: float64

In [14]:
df.groupby('Ship Mode')['Shipping Days'].agg(
    ['count', 'mean', 'median', 'min', 'max']
)

                count         mean  median  min   max
Ship Mode
First Class      1548  1360.131783  1299.0  522  1961
Same Day          547  1356.488117  1297.0  727  1929
Second Class     1979  1352.121273  1300.0  491  1960
Standard Class   6120  1336.575980  1276.0  552  1965

In [15]:
df.groupby('Region')['Shipping Days'].agg(
    ['count', 'mean', 'median', 'min', 'max']
).sort_values('mean', ascending=False)

          count         mean  median  min   max
Region
Atlantic   2986  1350.569658  1299.0  522  1963
Pacific    3253  1349.620658  1284.0  552  1965
Interior   2335  1343.312206  1276.0  522  1965
Gulf       1620  1323.101852  1275.0  491  1963

In [16]:
df['Profit Margin'] = (df['Gross Profit'] / df['Sales']) * 100

In [17]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Days,Profit Margin
0,1,US-2021-103800-CHO-MIL-31000,2024-03-01,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,851,64.923077
1,2,US-2021-112326-CHO-TRI-54000,2024-04-01,2026-01-07,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,646,65.333333
2,3,US-2021-112326-CHO-NUT-13000,2024-04-01,2026-01-07,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,646,71.346705
3,4,US-2021-112326-CHO-SCR-58000,2024-04-01,2026-01-07,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,646,69.444444
4,5,US-2021-141817-CHO-TRI-54000,2024-05-01,2026-05-07,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,736,65.333333

In [18]:
df[['Sales', 'Gross Profit', 'Profit Margin']].head()

   Sales  Gross Profit  Profit Margin
0   6.50          4.22      64.923077
1   7.50          4.90      65.333333
2  10.47          7.47      71.346705
3  10.80          7.50      69.444444
4  11.25          7.35      65.333333

In [19]:
df['Year'] = df['Order Date'].dt.year

In [24]:
df['Month'] = df['Order Date'].dt.month_name()

In [25]:
df['Month Number'] = df['Order Date'].dt.month

In [26]:
df[['Order Date', 'Shipping Days', 'Profit Margin', 'Year', 'Month', 'Month Number']].head()

  Order Date  Shipping Days  Profit Margin  Year  Month  Month Number
0 2024-03-01            851      64.923077  2024  March             3
1 2024-04-01            646      65.333333  2024  April             4
2 2024-04-01            646      71.346705  2024  April             4
3 2024-04-01            646      69.444444  2024  April             4
4 2024-05-01            736      65.333333  2024    May             5

In [27]:
#overall KPI

In [24]:
print("Total Sales:", df['Sales'].sum())

Total Sales: 141783.63

In [25]:
print("Total Cost:", df['Cost'].sum())

Total Cost: 48340.83

In [26]:
print("Total Gross Profit:", df['Gross Profit'].sum())

Total Gross Profit: 93442.79999999999

In [27]:
print("Total Units:", df['Units'].sum())

Total Units: 38654

In [28]:
print("Total Orders:", df['Order ID'].nunique())

Total Orders: 8549

In [29]:
print("Average Shipping Days:", df['Shipping Days'].mean())

Average Shipping Days: 1344.2393564842064

In [30]:
print("Overall Profit Margin:", (df['Gross Profit'].sum() / df['Sales'].sum()) * 100)

Overall Profit Margin: 65.90521063679917

In [31]:
#Region Analysis
region_analysis = df.groupby('Region').agg(
    Orders=('Order ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum'),
    Units=('Units', 'sum')
).sort_values('Sales', ascending=False)

region_analysis

          Orders     Sales  Gross_Profit  Units
Region
Pacific     2744  46301.53      30485.94  12466
Atlantic    2476  41197.24      26973.70  11159
Interior    1979  32037.60      21282.49   8820
Gulf        1350  22247.26      14700.67   6209

In [32]:
region_analysis['Profit Margin %'] = (
    region_analysis['Gross_Profit'] / region_analysis['Sales']
) * 100

region_analysis

          Orders     Sales  Gross_Profit  Units  Profit Margin %
Region
Pacific     2744  46301.53      30485.94  12466        65.842187
Atlantic    2476  41197.24      26973.70  11159        65.474532
Interior    1979  32037.60      21282.49   8820        66.429726
Gulf        1350  22247.26      14700.67   6209        66.078564

In [33]:
#Which Division generates the highest Sales and Gross Profit?
division_analysis = df.groupby('Division').agg(
    Orders=('Order ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum'),
    Units=('Units', 'sum')
).sort_values('Sales', ascending=False)

division_analysis

           Orders      Sales  Gross_Profit  Units
Division
Chocolate    8205  131692.90      88824.62  37275
Other         304    9663.25       4333.45   1242
Sugar          40     427.48        284.73    137

In [34]:
division_analysis['Profit Margin %'] = (
    division_analysis['Gross_Profit'] /
    division_analysis['Sales']
) * 100

division_analysis

           Orders      Sales  Gross_Profit  Units  Profit Margin %
Division
Chocolate    8205  131692.90      88824.62  37275        67.448298
Other         304    9663.25       4333.45   1242        44.844643
Sugar          40     427.48        284.73    137        66.606625

In [35]:
#Product Analysis
product_analysis = df.groupby('Product Name').agg(
    Orders=('Order ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum'),
    Units=('Units', 'sum')
).sort_values('Sales', ascending=False)

product_analysis.head(10)

                                   Orders     Sales  Gross_Profit  Units
Product Name
Wonka Bar - Triple Dazzle Caramel    1677  28485.00      18610.20   7596
Wonka Bar -Scrumdiddlyumptious       1704  27874.80      19357.50   7743
Wonka Bar - Milk Chocolate           1768  26867.75      17443.37   8267
Wonka Bar - Fudge Mallows            1527  24890.40      16593.60   6914
Wonka Bar - Nutty Crunch Surprise    1529  23574.95      16819.95   6755
Lickable Wallpaper                     92   7860.00       3930.00    393
Kazookles                              94   1205.75         92.75    371
Wonka Gum                             118    597.50        310.70    478
Everlasting Gobstopper                  3    130.00        104.00     13
Fizzy Lifting Drinks                    6     78.75         47.25     21

In [36]:
product_analysis['Profit Margin %'] = (
    product_analysis['Gross_Profit'] /
    product_analysis['Sales']
) * 100

In [37]:
product_analysis.head(10)

,Orders,Sales,Gross_Profit,Units,Profit Margin %
Product Name,,,,,
Wonka Bar - Triple Dazzle Caramel,1677,28485.00,18610.20,7596,65.333333
Wonka Bar -Scrumdiddlyumptious,1704,27874.80,19357.50,7743,69.444444
Wonka Bar - Milk Chocolate,1768,26867.75,17443.37,8267,64.923077
Wonka Bar - Fudge Mallows,1527,24890.40,16593.60,6914,66.666667
Wonka Bar - Nutty Crunch Surprise,1529,23574.95,16819.95,6755,71.346705
Lickable Wallpaper,92,7860.00,3930.00,393,50.000000
Kazookles,94,1205.75,92.75,371,7.692308
Wonka Gum,118,597.50,310.70,478,52.000000
Everlasting Gobstopper,3,130.00,104.00,13,80.000000
Fizzy Lifting Drinks,6,78.75,47.25,21,60.000000

In [38]:
top_profit_products = product_analysis.sort_values(
    'Gross_Profit',
    ascending=False
)

top_profit_products.head(10)

,Orders,Sales,Gross_Profit,Units,Profit Margin %
Product Name,,,,,
Wonka Bar -Scrumdiddlyumptious,1704,27874.80,19357.50,7743,69.444444
Wonka Bar - Triple Dazzle Caramel,1677,28485.00,18610.20,7596,65.333333
Wonka Bar - Milk Chocolate,1768,26867.75,17443.37,8267,64.923077
Wonka Bar - Nutty Crunch Surprise,1529,23574.95,16819.95,6755,71.346705
Wonka Bar - Fudge Mallows,1527,24890.40,16593.60,6914,66.666667
Lickable Wallpaper,92,7860.00,3930.00,393,50.000000
Wonka Gum,118,597.50,310.70,478,52.000000
Everlasting Gobstopper,3,130.00,104.00,13,80.000000
Kazookles,94,1205.75,92.75,371,7.692308
Hair Toffee,4,76.50,59.50,17,77.777778

In [39]:
#Low-profit products
low_margin_products = product_analysis.sort_values(
    'Profit Margin %',
    ascending=True
)

low_margin_products.head(10)

,Orders,Sales,Gross_Profit,Units,Profit Margin %
Product Name,,,,,
Kazookles,94,1205.75,92.75,371,7.692308
Fun Dip,3,12.00,4.80,8,40.000000
SweeTARTS,10,61.50,28.70,41,46.666667
Nerds,4,15.00,7.00,10,46.666667
Lickable Wallpaper,92,7860.00,3930.00,393,50.000000
Wonka Gum,118,597.50,310.70,478,52.000000
Fizzy Lifting Drinks,6,78.75,47.25,21,60.000000
Laffy Taffy,10,53.73,33.48,27,62.311558
Wonka Bar - Milk Chocolate,1768,26867.75,17443.37,8267,64.923077
Wonka Bar - Triple Dazzle Caramel,1677,28485.00,18610.20,7596,65.333333

In [40]:
#Time Analysis
year_analysis = df.groupby('Year').agg(
    Orders=('Order ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum'),
    Units=('Units', 'sum')
).sort_index()

year_analysis

      Orders     Sales  Gross_Profit  Units
Year
2024    3482  57956.20      38151.43  15899
2025    5067  83827.43      55291.37  22755

In [41]:
#year-over-year growth (%)
year_analysis['Sales Growth %'] = year_analysis['Sales'].pct_change() * 100
year_analysis['Profit Growth %'] = year_analysis['Gross_Profit'].pct_change() * 100

year_analysis

      Orders     Sales  Gross_Profit  Units  Sales Growth %  Profit Growth %
Year
2024    3482  57956.20      38151.43  15899             NaN              NaN
2025    5067  83827.43      55291.37  22755       44.639279        44.926075

In [42]:
year_analysis['Sales Growth %'] = year_analysis['Sales Growth %'].round(2)
year_analysis['Profit Growth %'] = year_analysis['Profit Growth %'].round(2)

year_analysis

      Orders     Sales  Gross_Profit  Units  Sales Growth %  Profit Growth %
Year
2024    3482  57956.20      38151.43  15899             NaN              NaN
2025    5067  83827.43      55291.37  22755           44.64            44.93

In [43]:
#Shipping Mode Analysis
shipping_mode_analysis = df.groupby('Ship Mode').agg(
    Orders=('Order ID', 'nunique'),
    Avg_Shipping_Days=('Shipping Days', 'mean'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum')
)

shipping_mode_analysis

                Orders  Avg_Shipping_Days     Sales  Gross_Profit
Ship Mode
First Class       1312        1360.131783  21319.39      14011.09
Same Day           442        1356.488117   7113.67       4700.73
Second Class      1653        1352.121273  27860.22      18306.52
Standard Class    5142        1336.575980  85490.35      56424.46

In [44]:
shipping_mode_analysis.sort_values(
    'Avg_Shipping_Days',
    ascending=False
)

                Orders  Avg_Shipping_Days     Sales  Gross_Profit
Ship Mode
First Class       1312        1360.131783  21319.39      14011.09
Same Day           442        1356.488117   7113.67       4700.73
Second Class      1653        1352.121273  27860.22      18306.52
Standard Class    5142        1336.575980  85490.35      56424.46

In [45]:
shipping_mode_analysis['Avg_Shipping_Days'] = (
    shipping_mode_analysis['Avg_Shipping_Days'].round(2)
)

shipping_mode_analysis

                Orders  Avg_Shipping_Days     Sales  Gross_Profit
Ship Mode
First Class       1312            1360.13  21319.39      14011.09
Same Day           442            1356.49   7113.67       4700.73
Second Class      1653            1352.12  27860.22      18306.52
Standard Class    5142            1336.58  85490.35      56424.46

In [46]:
#Region Shipping Analysis
region_shipping_analysis = df.groupby('Region').agg(
    Orders=('Order ID', 'nunique'),
    Avg_Shipping_Days=('Shipping Days', 'mean'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum')
)

region_shipping_analysis

          Orders  Avg_Shipping_Days     Sales  Gross_Profit
Region
Atlantic    2476        1350.569658  41197.24      26973.70
Gulf        1350        1323.101852  22247.26      14700.67
Interior    1979        1343.312206  32037.60      21282.49
Pacific     2744        1349.620658  46301.53      30485.94

In [47]:
region_shipping_analysis = region_shipping_analysis.sort_values(
    'Avg_Shipping_Days',
    ascending=False
)

region_shipping_analysis

          Orders  Avg_Shipping_Days     Sales  Gross_Profit
Region
Atlantic    2476        1350.569658  41197.24      26973.70
Pacific     2744        1349.620658  46301.53      30485.94
Interior    1979        1343.312206  32037.60      21282.49
Gulf        1350        1323.101852  22247.26      14700.67

In [48]:
#Which Division has the highest average shipping time?
division_shipping_analysis = df.groupby('Division').agg(
    Orders=('Order ID', 'nunique'),
    Avg_Shipping_Days=('Shipping Days', 'mean'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum')
).sort_values('Avg_Shipping_Days', ascending=False)

division_shipping_analysis

           Orders  Avg_Shipping_Days      Sales  Gross_Profit
Division
Sugar          40        1353.650000     427.48        284.73
Chocolate    8205        1344.678586  131692.90      88824.62
Other         304        1329.077419    9663.25       4333.45

In [49]:
#products have high sales but low profit margins
#products have high sales
high_sales_products = product_analysis.sort_values(
    'Sales',
    ascending=False
)

high_sales_products.head(10)

,Orders,Sales,Gross_Profit,Units,Profit Margin %
Product Name,,,,,
Wonka Bar - Triple Dazzle Caramel,1677,28485.00,18610.20,7596,65.333333
Wonka Bar -Scrumdiddlyumptious,1704,27874.80,19357.50,7743,69.444444
Wonka Bar - Milk Chocolate,1768,26867.75,17443.37,8267,64.923077
Wonka Bar - Fudge Mallows,1527,24890.40,16593.60,6914,66.666667
Wonka Bar - Nutty Crunch Surprise,1529,23574.95,16819.95,6755,71.346705
Lickable Wallpaper,92,7860.00,3930.00,393,50.000000
Kazookles,94,1205.75,92.75,371,7.692308
Wonka Gum,118,597.50,310.70,478,52.000000
Everlasting Gobstopper,3,130.00,104.00,13,80.000000
Fizzy Lifting Drinks,6,78.75,47.25,21,60.000000

In [50]:
#products with low profit margin
low_margin_products = product_analysis.sort_values(
    'Profit Margin %',
    ascending=True
)

low_margin_products.head(10)

,Orders,Sales,Gross_Profit,Units,Profit Margin %
Product Name,,,,,
Kazookles,94,1205.75,92.75,371,7.692308
Fun Dip,3,12.00,4.80,8,40.000000
SweeTARTS,10,61.50,28.70,41,46.666667
Nerds,4,15.00,7.00,10,46.666667
Lickable Wallpaper,92,7860.00,3930.00,393,50.000000
Wonka Gum,118,597.50,310.70,478,52.000000
Fizzy Lifting Drinks,6,78.75,47.25,21,60.000000
Laffy Taffy,10,53.73,33.48,27,62.311558
Wonka Bar - Milk Chocolate,1768,26867.75,17443.37,8267,64.923077
Wonka Bar - Triple Dazzle Caramel,1677,28485.00,18610.20,7596,65.333333

In [51]:
#products that have BOTH high sales and low margin
sales_threshold = product_analysis['Sales'].median()
margin_threshold = product_analysis['Profit Margin %'].median()

high_sales_low_margin = product_analysis[
    (product_analysis['Sales'] > sales_threshold) &
    (product_analysis['Profit Margin %'] < margin_threshold)
]

high_sales_low_margin.sort_values(
    'Sales',
    ascending=False
)

                    Orders    Sales  Gross_Profit  Units  Profit Margin %
Product Name
Lickable Wallpaper      92  7860.00       3930.00    393        50.000000
Kazookles               94  1205.75         92.75    371         7.692308

In [52]:
#region_shipping_analysis
#Find the thresholds
sales_threshold = region_shipping_analysis['Sales'].median()
shipping_threshold = region_shipping_analysis['Avg_Shipping_Days'].median()

print("Sales Threshold:", sales_threshold)
print("Shipping Threshold:", shipping_threshold)

Sales Threshold: 36617.42
Shipping Threshold: 1346.46643171087

In [53]:
#Find regions that have BOTH high sales and high shipping time
high_sales_high_shipping = region_shipping_analysis[
    (region_shipping_analysis['Sales'] > sales_threshold) &
    (region_shipping_analysis['Avg_Shipping_Days'] > shipping_threshold)
]

high_sales_high_shipping

          Orders  Avg_Shipping_Days     Sales  Gross_Profit
Region
Atlantic    2476        1350.569658  41197.24      26973.70
Pacific     2744        1349.620658  46301.53      30485.94

In [54]:
#Does higher shipping time appear to be associated with lower profit

#Calculate shipping time and profit for each product
product_shipping_analysis = df.groupby('Product Name').agg(
    Orders=('Order ID', 'nunique'),
    Avg_Shipping_Days=('Shipping Days', 'mean'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum')
).sort_values('Avg_Shipping_Days', ascending=False)

product_shipping_analysis.head(10)

,Orders,Avg_Shipping_Days,Sales,Gross_Profit
Product Name,,,,
SweeTARTS,10,1469.100000,61.50,28.70
Everlasting Gobstopper,3,1434.000000,130.00,104.00
Laffy Taffy,10,1421.900000,53.73,33.48
Lickable Wallpaper,92,1388.000000,7860.00,3930.00
Wonka Bar - Nutty Crunch Surprise,1529,1352.179558,23574.95,16819.95
Wonka Bar - Triple Dazzle Caramel,1677,1349.094789,28485.00,18610.20
Wonka Bar -Scrumdiddlyumptious,1704,1343.434593,27874.80,19357.50
Wonka Bar - Milk Chocolate,1768,1339.898924,26867.75,17443.37
Wonka Bar - Fudge Mallows,1527,1339.346535,24890.40,16593.60
Hair Toffee,4,1337.250000,76.50,59.50

In [55]:
#Calculate correlation
product_shipping_analysis[
    ['Avg_Shipping_Days', 'Gross_Profit']
].corr()

                   Avg_Shipping_Days  Gross_Profit
Avg_Shipping_Days           1.000000      0.142162
Gross_Profit                0.142162      1.000000

In [56]:
#Profit Margin % against shipping time
product_shipping_analysis['Profit Margin %'] = (
    product_shipping_analysis['Gross_Profit'] /
    product_shipping_analysis['Sales']
) * 100

In [57]:
product_shipping_analysis[
    ['Avg_Shipping_Days', 'Profit Margin %']
].corr()

                   Avg_Shipping_Days  Profit Margin %
Avg_Shipping_Days           1.000000         0.337717
Profit Margin %             0.337717         1.000000

In [58]:
#Analysis: High Sales + Low Profit Margin

#Find the sales threshold
sales_threshold = product_analysis['Sales'].median()

print("Sales Threshold:", sales_threshold)

Sales Threshold: 597.5

In [59]:
#Find the median profit margin
margin_threshold = product_analysis['Profit Margin %'].median()

print("Profit Margin Threshold:", margin_threshold)

Profit Margin Threshold: 62.31155778894474

In [60]:
#Find the products
high_sales_low_margin = product_analysis[
    (product_analysis['Sales'] > sales_threshold) &
    (product_analysis['Profit Margin %'] < margin_threshold)
].sort_values('Sales', ascending=False)

high_sales_low_margin

                    Orders    Sales  Gross_Profit  Units  Profit Margin %
Product Name
Lickable Wallpaper      92  7860.00       3930.00    393        50.000000
Kazookles               94  1205.75         92.75    371         7.692308

In [61]:
#Monthly Sales & Profit Trend

#Group by Year and Month
monthly_analysis = df.groupby(
    ['Year', 'Month Number']
).agg(
    Orders=('Order ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum'),
    Units=('Units', 'sum')
).reset_index()

monthly_analysis

    Year  Month Number  Orders    Sales  Gross_Profit  Units
0   2024             1     182  3163.41       2100.51    890
1   2024             2     168  2754.90       1804.30    748
2   2024             3     281  4461.74       2866.82   1206
3   2024             4     238  3855.48       2515.19   1039
4   2024             5     290  4868.48       3173.74   1296
5   2024             6     250  3633.97       2426.03   1039
6   2024             7     249  3986.35       2650.91   1148
7   2024             8     281  4818.74       3180.82   1332
8   2024             9     422  7351.58       4822.82   1959
9   2024            10     250  4397.98       2881.62   1161
10  2024            11     441  7587.11       5058.37   2143
11  2024            12     430  7076.46       4670.30   1938
12  2025             1     326  5475.58       3647.43   1534
13  2025             2     310  5688.88       3647.62   1414
14  2025             3     422  7001.29       4631.43   1914
15  2025             4     372  5564.95       3642.13   1496
16  2025             5     427  7349.62       4818.02   1960
17  2025             6     362  5586.66       3753.73   1588
18  2025             7     385  6199.52       4103.38   1681
19  2025             8     420  7031.29       4669.52   1961
20  2025             9     528  8686.81       5700.83   2293
21  2025            10     443  7325.07       4818.41   1951
22  2025            11     563  9396.35       6227.20   2642
23  2025            12     509  8521.41       5631.67   2321

In [62]:
#Calculate monthly profit margin
monthly_analysis['Profit Margin %'] = (
    monthly_analysis['Gross_Profit'] /
    monthly_analysis['Sales']
) * 100

In [63]:
#Sort chronologically
monthly_analysis = monthly_analysis.sort_values(
    ['Year', 'Month Number']
)
monthly_analysis

    Year  Month Number  Orders    Sales  Gross_Profit  Units  Profit Margin %
0   2024             1     182  3163.41       2100.51    890        66.400182
1   2024             2     168  2754.90       1804.30    748        65.494210
2   2024             3     281  4461.74       2866.82   1206        64.253408
3   2024             4     238  3855.48       2515.19   1039        65.236754
4   2024             5     290  4868.48       3173.74   1296        65.189546
5   2024             6     250  3633.97       2426.03   1039        66.759770
6   2024             7     249  3986.35       2650.91   1148        66.499680
7   2024             8     281  4818.74       3180.82   1332        66.009372
8   2024             9     422  7351.58       4822.82   1959        65.602496
9   2024            10     250  4397.98       2881.62   1161        65.521444
10  2024            11     441  7587.11       5058.37   2143        66.670577
11  2024            12     430  7076.46       4670.30   1938        65.997688
12  2025             1     326  5475.58       3647.43   1534        66.612669
13  2025             2     310  5688.88       3647.62   1414        64.118420
14  2025             3     422  7001.29       4631.43   1914        66.151095
15  2025             4     372  5564.95       3642.13   1496        65.447668
16  2025             5     427  7349.62       4818.02   1960        65.554682
17  2025             6     362  5586.66       3753.73   1588        67.190951
18  2025             7     385  6199.52       4103.38   1681        66.188673
19  2025             8     420  7031.29       4669.52   1961        66.410573
20  2025             9     528  8686.81       5700.83   2293        65.626277
21  2025            10     443  7325.07       4818.41   1951        65.779713
22  2025            11     563  9396.35       6227.20   2642        66.272542
23  2025            12     509  8521.41       5631.67   2321        66.088476

In [64]:
#highest-sales month
best_sales_month = monthly_analysis.loc[
    monthly_analysis['Sales'].idxmax()
]

best_sales_month

Year               2025.000000
Month Number         11.000000
Orders              563.000000
Sales              9396.350000
Gross_Profit       6227.200000
Units              2642.000000
Profit Margin %      66.272542
Name: 22, dtype: float64

In [65]:
#lowest-sales month
worst_sales_month = monthly_analysis.loc[
    monthly_analysis['Sales'].idxmin()
]

worst_sales_month

Year               2024.00000
Month Number          2.00000
Orders              168.00000
Sales              2754.90000
Gross_Profit       1804.30000
Units               748.00000
Profit Margin %      65.49421
Name: 1, dtype: float64

In [66]:
#Top-performing regions over time
region_year_analysis = df.groupby(
    ['Year', 'Region']
).agg(
    Orders=('Order ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Gross_Profit=('Gross Profit', 'sum'),
    Units=('Units', 'sum')
).reset_index()

region_year_analysis

   Year    Region  Orders     Sales  Gross_Profit  Units
0  2024  Atlantic    1004  16960.18      11072.36   4613
1  2024      Gulf     566   9561.03       6300.97   2680
2  2024  Interior     788  12693.81       8414.50   3541
3  2024   Pacific    1124  18741.18      12363.60   5065
4  2025  Atlantic    1472  24237.06      15901.34   6546
5  2025      Gulf     784  12686.23       8399.70   3529
6  2025  Interior    1191  19343.79      12867.99   5279
7  2025   Pacific    1620  27560.35      18122.34   7401

In [67]:
#Which region grew the most from 2024 to 2025?

#Calculate regional sales growth
region_growth = region_year_analysis.pivot(
    index='Region',
    columns='Year',
    values='Sales'
)

region_growth['Sales Growth %'] = (
    (region_growth[2025] - region_growth[2024])
    / region_growth[2024]
) * 100

region_growth.sort_values('Sales Growth %', ascending=False)

Year          2024      2025  Sales Growth %
Region
Interior  12693.81  19343.79       52.387581
Pacific   18741.18  27560.35       47.057709
Atlantic  16960.18  24237.06       42.905677
Gulf       9561.03  12686.23       32.686855

In [68]:
#Let's check whether profit grew at the same rate as sales for each region.
region_profit_growth = region_year_analysis.pivot(
    index='Region',
    columns='Year',
    values='Gross_Profit'
)

region_profit_growth['Profit Growth %'] = (
    (region_profit_growth[2025] - region_profit_growth[2024])
    / region_profit_growth[2024]
) * 100

region_profit_growth.sort_values('Profit Growth %', ascending=False)

Year          2024      2025  Profit Growth %
Region
Interior   8414.50  12867.99        52.926377
Pacific   12363.60  18122.34        46.578181
Atlantic  11072.36  15901.34        43.612924
Gulf       6300.97   8399.70        33.308046

In [69]:
df.to_csv('Nassau_Candy_Cleaned.csv', index=False)

In [70]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:jasrotia007@localhost/nassau_candy")

df.to_sql(
    'nassau_candy_data',
    con=engine,
    if_exists='replace',
    index=False
)

10194

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  datetime64[us]
 3   Ship Date       10194 non-null  datetime64[us]
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
 18  Shipping Days   10194 non-null  int64
 19  Profit Margin   10194 non-null  float64
 20  Year            10194 non-null  int32
 21  Month           10194 non-null  str
 22  Month Number    10194 non-null  int32
dtypes: datetime64[us](2), float64(4), int32(2), int64(4), str(11)
memory usage: 1.7 MB